name: pokemon
description: Get a random name from Pok√©mon creatures, available in multiple languages.
version: 1.0.0
repository: https://github.com/javoeria/pokemon-names

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - pokemon
  - random
  - placeholder
